# Generated by Django 4.1.13 on 2026-03-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_avatar_thumbnail'),
        ('users', '0006_alter_userprofile_avatar'),
    ]

    operations = [
    ]
