# Generated by Django 4.1.13 on 2026-03-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_merge_20260320_0727"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pixo_balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rewarded_pixels_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PixoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("email_verified", "Email verified"),
                            ("pixel_milestone", "Pixel milestone"),
                        ],
                        max_length=32,
                    ),
                ),
                ("context_key", models.CharField(max_length=128, unique=True)),
                ("details", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pixo_transactions",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
