# Generated by Django 4.1.13 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userprofile_pixo_and_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixotransaction",
            name="balance_after",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pixotransaction",
            name="balance_before",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pixotransaction",
            name="entry_type",
            field=models.CharField(
                choices=[("credit", "Credit"), ("debit", "Debit")],
                default="credit",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="pixotransaction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pixotransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("email_verified", "Email verified"),
                    ("pixel_milestone", "Pixel milestone"),
                    ("feature_spend", "Feature spend"),
                    ("manual_adjustment", "Manual adjustment"),
                ],
                max_length=32,
            ),
        ),
    ]
