# Generated by Django 4.1.13 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pixotransaction",
            name="balance_after",
        ),
        migrations.RemoveField(
            model_name="pixotransaction",
            name="balance_before",
        ),
        migrations.RemoveField(
            model_name="pixotransaction",
            name="entry_type",
        ),
        migrations.AlterField(
            model_name="pixotransaction",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
