# Generated by Django 4.1.13 on 2026-03-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pixelwar", "0010_alter_community_image"),
        ("users", "0011_signed_pixo_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pixotransaction",
            name="reason",
            field=models.CharField(
                choices=[
                    ("email_verified", "Email verified"),
                    ("pixel_milestone", "Pixel milestone"),
                    ("referral_community_join", "Referral community join"),
                    ("referral_milestone", "Referral milestone"),
                    ("feature_spend", "Feature spend"),
                    ("manual_adjustment", "Manual adjustment"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ReferralAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("community_invite", "Community invite"),
                            ("personal_link", "Personal link"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone_10_rewarded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_attributions",
                        to="pixelwar.community",
                    ),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_attribution",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="referralattribution",
            index=models.Index(fields=["referrer_user"], name="users_refer_referre_17821b_idx"),
        ),
        migrations.AddIndex(
            model_name="referralattribution",
            index=models.Index(fields=["created_at"], name="users_refer_created_6dca88_idx"),
        ),
    ]
