# Generated by Django 4.1.13 on 2026-03-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_referral_attribution_and_pixo_reasons'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralattribution',
            new_name='users_refer_referre_55cea2_idx',
            old_name='users_refer_referre_17821b_idx',
        ),
        migrations.RenameIndex(
            model_name='referralattribution',
            new_name='users_refer_created_6db8d4_idx',
            old_name='users_refer_created_6dca88_idx',
        ),
    ]
