# Generated by Django 5.2.12 on 2026-03-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwar', '0004_community_multitenancy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communitymembership',
            new_name='pixelwar_co_user_id_9a897e_idx',
            old_name='pixelwar_co_user_id_c72e78_idx',
        ),
        migrations.RenameIndex(
            model_name='pixel',
            new_name='pixelwar_pi_communi_cbd639_idx',
            old_name='pixelwar_pi_communi_d5af66_idx',
        ),
        migrations.RenameIndex(
            model_name='useraction',
            new_name='pixelwar_us_communi_6b6d4d_idx',
            old_name='pixelwar_us_communi_736ed9_idx',
        ),
    ]
