# Generated by Django 4.1.13 on 2026-03-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwar', '0006_public_communities_and_join_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityjoinrequest',
            new_name='pixelwar_co_communi_213219_idx',
            old_name='pixelwar_co_communi_0ab325_idx',
        ),
    ]
