# Generated by Django 4.1.13 on 2026-03-21 07:45

from django.db import migrations, models
import pixelwar.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelwar', '0009_community_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pixelwar.models.community_image_upload_path),
        ),
    ]
