# Generated by Django 4.1.13 on 2026-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification_visuals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='Notificatio_recipie_b57f30_idx',
            old_name='Notifications_recipient_6a4d95_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system_notice', 'System notice'), ('email_confirmed', 'Email confirmed'), ('email_change_pending', 'Email change pending'), ('join_request', 'Join request'), ('join_approved', 'Join approved'), ('join_declined', 'Join declined')], max_length=32),
        ),
    ]
